#!/usr/bin/env bash
#
# ufetch- tiny system information tool written in bash
#

## COLORS
RCol='\e[0m'     # Text Reset
c0='\033[33;31m' # Red
c1='\033[33;32m' # Green
c2='\033[33;33m' # Yellow
c3='\033[33;34m' # Blue
c4='\033[33;35m' # Magenta
c5='\033[33;30m' # Gray
c6='\033[33;36m' # Cyan

## INFO
host="$(hostname)@${USER}"
os="$(lsb_release -sd)"
uptime="$(uptime -p)"
shell="$(basename ${SHELL})"
cpu=$(awk -F ":" 'NR==5 {print $2}' /proc/cpuinfo)
gpu=$(lspci 2>/dev/null | awk -F ":" '/VGA/ {print $3}')
mem=$(awk '/MemTotal/ {print $2/1024}' /proc/meminfo)' MB'

## FUNCTIONS
function separator() {
    size=$1
    separator=$(printf "%${size}s");
    echo ${separator// /-}
}

## PRINT
echo -e ${c0}$host${RCol}
separator ${#host}

echo -e ${c1}OS:${RCol} $os
echo -e ${c2}UPTIME:${RCol} $uptime
echo -e ${c3}SHELL:${RCol} $shell
echo -e ${c4}CPU:${RCol} $cpu
echo -e ${c0}GPU:${RCol} $gpu
echo -e ${c6}RAM:${RCol} $mem $unit
echo -e
echo -e ${c0}███${RCol}${c1}███${RCol}${c2}███${RCol}${c3}███${Rcol}${c4}███${RCol}${c5}███${RCol}${c6}███${RCol}███${RCol}
echo -e
