#!/usr/bin/env bash
#
# ufetch- tiny system information tool written in bash
#

## COLORS
RCol='\e[0m'     # Text Reset
c0='\033[33;31m' # Red
c1='\033[33;32m' # Green
c2='\033[33;33m' # Yellow
c3='\033[33;34m' # Blue
c4='\033[33;35m' # Magenta
c5='\033[33;30m' # Gray
c6='\033[33;36m' # Cyan

## INFO
host="$(hostname)@${USER}"
os="$(lsb_release -sd)"
uptime="$(uptime -p)"
shell="$(basename ${SHELL})"
cpu=$(awk -F ":" 'NR==5 {print $2}' /proc/cpuinfo)
gpu=$(lspci 2>/dev/null | awk -F ":" '/VGA/ {print $3}')
mem=$(awk '/MemTotal/ {print $2/1024}' /proc/meminfo)' MB'

## FUNCTIONS
function separator() {
    size=$1
    separator=$(printf "%${size}s");
    echo ${separator// /-}
}

## PRINT
max_length=$(($(echo -n 'UPTIME' | wc -c) + 1))

echo -e ${c0}$host${RCol}
separator ${#host}

printf ${c1}"%-${max_length}s" 'OS'
echo -e ${RCol} $os

printf ${c2}"%-${max_length}s" 'UPTIME'
echo -e ${RCol} $uptime

printf ${c3}"%-${max_length}s" 'SHELL'
echo -e ${RCol} $shell

printf ${c4}"%-${max_length}s" 'CPU'
echo -e ${RCol} $cpu

printf ${c0}"%-${max_length}s" 'GPU'
echo -e ${RCol} $gpu

printf ${c6}"%-${max_length}s" 'RAM'
echo -e ${RCol} $mem $unit
echo -e
echo -e ${c0}███${RCol}${c1}███${RCol}${c2}███${RCol}${c3}███${Rcol}${c4}███${RCol}${c5}███${RCol}${c6}███${RCol}███${RCol}
echo -e
